### ISSUE TITLE
problem while trying to follow

### ISSUE THREAD

**Issue by ghost** [SkullTech/twitter-follow-bot#4]
Hello,

Thanks for the nice piece of code. I am not much familiar with Python but PHP.

To make your code execute the follow i had to put a time.sleep(2) for example right after the follow.click() without it the follow does not happen. 

Also can you write a function for like a given url? I checked at the class="HeartAnimation" but i don't know how to check the return.

Thank you so much.

**Comment by skulltech** [comment]
Hi @tbdsilva. I'm almost 1.5 years late to this issue but still, I added the `sleep`, you're right without that it wasn't working. And I didn't really get what you meant by writing a function for a given url. I'm sure you don't need this anymore but feel free to reopen the issue if you do. 

Thanks!
